[package]
name = "md5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8"
num_cpus = "0.2"
hex="0.4.3"

[profile.dev]
overflow-checks = false

rustflags = ["-Ctarget-cpu=native"]
